'use strict';
const KEY='caltrack_final_v1';
const DEF={profile:{age:35,sex:'female',height:170,current:90,goal:75,goalDate:'2026-12-26',activity:1.55,floor:1200},entries:[],foods:[],water:{}};
let S=load(),ocrBusy=false; const $=id=>document.getElementById(id),today=()=>new Date().toLocaleDateString('en-CA'),esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=n=>Math.round(n).toLocaleString();
function load(){try{let x=JSON.parse(localStorage.getItem(KEY));return x?{...DEF,...x,profile:{...DEF.profile,...x.profile},foods:x.foods||[],water:x.water||{}}:structuredClone(DEF)}catch{return structuredClone(DEF)}}
function save(){localStorage.setItem(KEY,JSON.stringify(S));render()}
function target(p=S.profile){let b=10*p.current+6.25*p.height-5*p.age+(p.sex==='male'?5:-161),m=b*+p.activity,days=Math.max(1,Math.ceil((new Date(p.goalDate+'T12:00:00')-new Date(today()+'T12:00:00'))/864e5)),def=Math.max(0,(p.current-p.goal)*7700/days),cal=Math.round(Math.max(+p.floor,m-def)/10)*10,protein=Math.round(p.current*1.4),fat=Math.round(cal*.28/9),fiber=25,carbs=Math.max(0,Math.round((cal-protein*4-fat*9)/4));return{b,m,days,def,cal,protein,fat,fiber,carbs,weekly:(p.current-p.goal)/(days/7)}}
const day=()=> $('date').value||today();
function totals(d){let e=S.entries.filter(x=>x.date===d),foods=e.filter(x=>x.kind==='food'),sum=k=>foods.reduce((a,x)=>a+(x[k]||0),0),food=foods.reduce((a,x)=>a+x.amount,0),out=e.filter(x=>x.kind==='exercise').reduce((a,x)=>a+x.amount,0),t=target();return{e,food,out,remain:t.cal-food+out,protein:sum('protein'),carbs:sum('carbs'),fat:sum('fat'),fiber:sum('fiber')}}
function add(x){S.entries.push({...x,id:crypto.randomUUID(),date:day(),time:new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})});save()}
$('date').value=today(); $('today').onclick=()=>{$('date').value=today();render()}; $('date').onchange=render; $('water').onclick=()=>{S.water[day()]=(S.water[day()]||0)+50;save()};
$('entryForm').onsubmit=e=>{e.preventDefault();let kind=$('kind').value,a=+$('amount').value;add({kind,description:$('description').value,amount:a,quantity:$('quantity').value,protein:+$('protein').value||0,carbs:+$('carbs').value||0,fat:+$('fat').value||0,fiber:+$('fiber').value||0});if(kind==='weight')S.profile.current=a;e.target.reset();save()};
window.deleteEntry=id=>{S.entries=S.entries.filter(x=>x.id!==id);save()};
function unitQuery(raw){let m=raw.match(/(\d+(?:\.\d+)?)\s*(ml|g|grams?|servings?)\b/i);return m?{n:+m[1],unit:m[2].toLowerCase().startsWith('serv')?'serving':m[2].toLowerCase().startsWith('g')?'g':'ml'}:null}
$('mealSearchBtn').onclick=()=>{let raw=$('mealSearch').value.trim(),u=unitQuery(raw),words=raw.replace(/\d+(?:\.\d+)?\s*(ml|g|grams?|servings?)\b/ig,'').trim().toLowerCase(),matches=S.foods.filter(f=>f.name.toLowerCase().includes(words)||words.split(/\s+/).filter(Boolean).every(w=>f.name.toLowerCase().includes(w)));$('mealMessage').textContent=`Searched ${S.foods.length} saved foods.`;$('mealResults').innerHTML=matches.length?matches.map(f=>{let req=u&&u.unit===f.unit?u.n:f.serving,fac=req/f.serving;return `<div class=result><div><b>${esc(f.name)}</b><br><small>${(f.calories*fac).toFixed(0)} kcal · P ${(f.protein*fac).toFixed(1)}g · C ${(f.carbs*fac).toFixed(1)}g · F ${(f.fat*fac).toFixed(1)}g · Fiber ${(f.fiber*fac).toFixed(1)}g for ${req} ${f.unit}</small></div><button onclick="useFood('${f.id}',${req})" class=primary>Use</button></div>`}).join(''):'<p>No Food List match. Open Food List to create or scan this product.</p>'};
window.useFood=(id,req)=>{let f=S.foods.find(x=>x.id===id);if(!f)return;let fac=(req||f.serving)/f.serving;$('kind').value='food';$('description').value=f.name;$('quantity').value=`${req||f.serving} ${f.unit}`;$('amount').value=(f.calories*fac).toFixed(0);$('protein').value=(f.protein*fac).toFixed(1);$('carbs').value=(f.carbs*fac).toFixed(1);$('fat').value=(f.fat*fac).toFixed(1);$('fiber').value=(f.fiber*fac).toFixed(1);$('foodDialog').close();$('entryForm').scrollIntoView({behavior:'smooth'})};
function renderFoods(){ $('foodRows').innerHTML=S.foods.length?S.foods.map(f=>`<div class=result><div><b>${esc(f.name)}</b><br><small>${f.calories} kcal · P ${f.protein}g · C ${f.carbs}g · F ${f.fat}g · Fiber ${f.fiber}g per ${f.serving} ${f.unit} · ${esc(f.source)}</small></div><div><button onclick="editFood('${f.id}')">Edit</button><button onclick="removeFood('${f.id}')" class=delete>×</button></div></div>`).join(''):'<p>No foods saved yet.</p>'}
function clearFood(){['foodId','foodName','foodCalories','foodProtein','foodCarbs','foodFat','foodFiber'].forEach(id=>$(id).value='');$('foodServing').value=100;$('foodUnit').value='ml';$('foodSource').value='Product label scan'}
$('foodListBtn').onclick=()=>{clearFood();renderFoods();$('foodDialog').showModal()};$('closeFood').onclick=()=>$('foodDialog').close();
$('foodForm').onsubmit=e=>{e.preventDefault();let id=$('foodId').value||crypto.randomUUID(),f={id,name:$('foodName').value.trim(),serving:+$('foodServing').value||100,unit:$('foodUnit').value,calories:+$('foodCalories').value,protein:+$('foodProtein').value||0,carbs:+$('foodCarbs').value||0,fat:+$('foodFat').value||0,fiber:+$('foodFiber').value||0,source:$('foodSource').value},i=S.foods.findIndex(x=>x.id===id);i>=0?S.foods[i]=f:S.foods.push(f);save();clearFood();renderFoods();$('ocrStatus').textContent='Food saved.'};
window.editFood=id=>{let f=S.foods.find(x=>x.id===id);if(!f)return;for(let [id,k] of [['foodId','id'],['foodName','name'],['foodServing','serving'],['foodUnit','unit'],['foodCalories','calories'],['foodProtein','protein'],['foodCarbs','carbs'],['foodFat','fat'],['foodFiber','fiber'],['foodSource','source']])$(id).value=f[k]};window.removeFood=id=>{if(confirm('Delete this food?')){S.foods=S.foods.filter(x=>x.id!==id);save();renderFoods()}};
function goGoogle(extra=''){let q=$('foodName').value.trim()||$('mealSearch').value.trim();if(q)open('https://www.google.com/search?q='+encodeURIComponent(q+' nutrition facts '+extra),'_blank','noopener')}$('googleBtn').onclick=()=>goGoogle();$('manufacturerBtn').onclick=()=>goGoogle('official manufacturer');
$('scanBtn').onclick=()=>$('photo').click(); $('photo').onchange=async e=>{let file=e.target.files?.[0];if(!file||ocrBusy)return;if(!window.Tesseract){$('ocrStatus').textContent='OCR library unavailable. Check internet and reload.';return}ocrBusy=true;$('ocrStatus').textContent='Reading label…';try{let {data:{text}}=await Tesseract.recognize(file,'eng',{logger:m=>{if(m.status==='recognizing text')$('ocrStatus').textContent=`Reading label… ${Math.round((m.progress||0)*100)}%`}});parseLabel(text);$('ocrStatus').textContent='Label read. Check kcal versus kJ and per-serving versus per-100 values before saving.'}catch{$('ocrStatus').textContent='Could not read label. Try a straight, well-lit close photo.'}finally{ocrBusy=false}};
function first(t,arr){for(let r of arr){let m=t.match(r);if(m)return +(m[1].replace(',','.'))}return ''}function parseLabel(t){let serving=first(t,[/(?:serving size|per serving|per 100\s*(?:g|ml))[^\d]{0,18}(\d+(?:[.,]\d+)?)/i]),kcal=first(t,[/(?:energy|calories?)[^\n\d]{0,20}(\d+(?:[.,]\d+)?)\s*kcal/i,/(\d+(?:[.,]\d+)?)\s*kcal/i]);$('foodServing').value=serving||100;$('foodUnit').value=/100\s*ml|serving size[^\n]*ml/i.test(t)?'ml':/per serving/i.test(t)?'serving':'g';$('foodCalories').value=kcal;$('foodProtein').value=first(t,[/protein[^\d]{0,18}(\d+(?:[.,]\d+)?)\s*g/i]);$('foodCarbs').value=first(t,[/(?:total\s+)?carbohydrate[^\d]{0,18}(\d+(?:[.,]\d+)?)\s*g/i,/carbs?[^\d]{0,18}(\d+(?:[.,]\d+)?)\s*g/i]);$('foodFat').value=first(t,[/(?:total\s+)?fat[^\d]{0,18}(\d+(?:[.,]\d+)?)\s*g/i]);$('foodFiber').value=first(t,[/(?:dietary\s+)?fi(?:ber|bre)[^\d]{0,18}(\d+(?:[.,]\d+)?)\s*g/i])}
$('profileBtn').onclick=()=>{let p=S.profile;for(let [id,k] of [['pAge','age'],['pSex','sex'],['pHeight','height'],['pCurrent','current'],['pGoal','goal'],['pGoalDate','goalDate'],['pActivity','activity'],['pFloor','floor']])$(id).value=p[k];preview();$('profileDialog').showModal()};$('closeProfile').onclick=()=>$('profileDialog').close();document.querySelectorAll('#profileForm input,#profileForm select').forEach(x=>x.oninput=preview);function preview(){let p={age:+$('pAge').value,sex:$('pSex').value,height:+$('pHeight').value,current:+$('pCurrent').value,goal:+$('pGoal').value,goalDate:$('pGoalDate').value,activity:+$('pActivity').value,floor:+$('pFloor').value},t=target(p);$('profilePreview').textContent=`Target ${fmt(t.cal)} kcal · Protein ${t.protein}g · Carbs ${t.carbs}g · Fat ${t.fat}g · Fiber ${t.fiber}g · Required ${t.weekly.toFixed(2)} kg/week`}$('profileForm').onsubmit=e=>{e.preventDefault();S.profile={age:+$('pAge').value,sex:$('pSex').value,height:+$('pHeight').value,current:+$('pCurrent').value,goal:+$('pGoal').value,goalDate:$('pGoalDate').value,activity:+$('pActivity').value,floor:+$('pFloor').value};$('profileDialog').close();save()};
$('export').onclick=()=>{let a=document.createElement('a'),u=URL.createObjectURL(new Blob([JSON.stringify(S,null,2)],{type:'application/json'}));a.href=u;a.download='caltrack-full-backup.json';a.click();URL.revokeObjectURL(u)};$('import').onchange=async e=>{try{let x=JSON.parse(await e.target.files[0].text());if(!x.profile||!Array.isArray(x.entries)||!Array.isArray(x.foods))throw 0;S=x;S.water||={};save();alert('Full backup imported.')}catch{alert('Invalid CalTrack full backup.')}};
function ring(id,p){$(id).style.setProperty('--p',Math.max(0,Math.min(100,p)))}function macro(name,used,max){$(name+'Left').textContent=`${Math.max(0,Math.round(max-used))} g`;$(`${name}Bar`).value=Math.min(100,used/max*100);$(name+'Used').textContent=`${Math.round(used)} of ${max} g used`}
function draw(){let c=$('chart'),r=devicePixelRatio,w=c.clientWidth,h=220,ctx=c.getContext('2d');c.width=w*r;c.height=h*r;ctx.scale(r,r);let base=new Date(day()+'T12:00:00'),data=[];for(let i=6;i>=0;i--){let d=new Date(base);d.setDate(d.getDate()-i);let ds=d.toLocaleDateString('en-CA');data.push({l:ds.slice(5),v:totals(ds).food})}let tg=target().cal,max=Math.max(tg,...data.map(x=>x.v),1)*1.15,p=24,pw=w-p-6,ph=h-38;ctx.clearRect(0,0,w,h);data.forEach((x,i)=>{let bh=x.v/max*ph,x0=p+i*pw/7+5;ctx.fillStyle='#ff2d55';ctx.fillRect(x0,8+ph-bh,pw/7-10,bh);ctx.fillStyle='#888';ctx.font='10px system-ui';ctx.textAlign='center';ctx.fillText(x.l,x0+(pw/7-10)/2,h-5)})}
function render(){let d=day(),x=totals(d),t=target(),water=S.water[d]||0;$('dateLabel').textContent=new Date(d+'T12:00:00').toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'});$('remaining').textContent=$('ringRemain').textContent=fmt(x.remain);$('target').textContent=fmt(t.cal);$('food').textContent=fmt(x.food);$('out').textContent=fmt(x.out);ring('calRing',x.food/t.cal*100);ring('proteinRing',x.protein/t.protein*100);ring('waterRing',water/2500*100);macro('protein',x.protein,t.protein);macro('carbs',x.carbs,t.carbs);macro('fat',x.fat,t.fat);macro('fiber',x.fiber,t.fiber);$('goalNote').textContent=`${(water/1000).toFixed(2)} L water · ${t.days} days to ${S.profile.goal} kg goal`;$('log').innerHTML=x.e.length?x.e.map(e=>`<tr><td>${e.time}</td><td>${esc(e.description)}</td><td>${fmt(e.amount)} ${e.kind==='weight'?'kg':'kcal'}</td><td><button class=delete onclick="deleteEntry('${e.id}')">×</button></td></tr>`).join(''):'<tr><td colspan=4>No entries yet.</td></tr>';$('analysis').innerHTML=`Maintenance estimate: <b>${fmt(t.m)} kcal/day</b><br>Goal-derived deficit: <b>${fmt(t.def)} kcal/day</b><br>Required pace: <b>${t.weekly.toFixed(2)} kg/week</b>${t.weekly>.9?'<div class=notice>This is an aggressive required pace. Consider changing the goal date or consulting a qualified professional.</div>':''}`;draw()}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');render();
